### ISSUE TITLE
GPU lockup

### ISSUE THREAD

**Issue by ZXGuesser** [ali1234/raspi-teletext#20] opened 2018-10-12 18:22 UTC
I've been having a peculiar problem with the system I'm building for the imminent Block Party event next weekend. The system has four pi zeros each outputting video with teletext. Every so often the video of a pi will freeze up and GPU stuff hangs until the teletext process is killed (at which point video playback etc resumes).
Once the teletext process has been killed the following line appears in the kernel log
`vchiq: 0: ignoring ERROR from callback to service`

I've been running my own fork for individual assignment of VBI lines through most of my testing trying to narrow the issue, but I've checked the upstream code this evening and the same freezes occur.
I'm playing out video using omxplayer, but the same freezes happen whether video is running or not (and don't occur during playback without teletext active)

**Comment by ali1234** [comment] 2018-10-13 02:43
I think I know what the problem is.

Try commenting out this line: https://github.com/ali1234/raspi-teletext/blob/master/teletext.c#L150

See the bug report in the comment above for why it is there - but the bug should be fixed now.

**Comment by ali1234** [comment] 2018-10-13 02:45
Alternatively if that does not work then likely the bug is not actually fixed in the firmware and there isn't much I can do about that. The vsync callback was always really buggy if two programs were using it at the same time and it is very likely omxplayer uses it and will freeze up if it does not get a vsync callback.

**Comment by ali1234** [comment] 2018-10-13 09:31
It is also possible that this is a regression so try older firmware and kernel.

**Closed** 2019-09-04 19:57 UTC
